http://localhost/phpmyadmin/export.php?what=sql&db_select[]=peopledb&sql_drop_database=something&sql_header_comment=""&sql_compatibility="NONE"&sql_drop_database="something"&sql_structure="something"&sql_if_not_exists="something"&sql_auto_increment="something"&sql_backquotes"something"&sql_data="something"&sql_columns="something"&sql_extended="something"&ql_max_query_size="50000"&sql_hex_for_binary="something"&sql_type="0"&asfile="sendit"
////////////////////////
name="sql_header_comment" value=""
name="sql_compatibility" name="NONE"
name="sql_drop_database" value="something"
name="sql_structure" value="something"
name="sql_if_not_exists" value="something"
name="sql_auto_increment" value="something"
name="sql_backquotes" value="something"
name="sql_data" value="something"
name="sql_columns" value="something" 
name="sql_extended" value="something"
name="sql_max_query_size" value="50000"
name="sql_hex_for_binary" value="something" 
name="sql_type" name="0"
name="asfile" value="sendit"